### ISSUE TITLE
API level 

### ISSUE THREAD

**Issue by Usama75** [codeWithCal/CalendarTutorialAndroidStudio#1]
your Calendar app work API level greater then 26 could you give support API level less then 26?

**Comment by codeWithCal** [comment]
Hi it's all about the convenience of using Javas Localdate.
No reason you couldn't rewrite all the methods to use java util date or
something.

I choose Localdate more to show a concept. And being a tutorial trying to
make it as short as possible.


Good luck,

Cheers Cal
